concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
    runs-on: ["${{ matrix.os }}"]
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: |
          sudo apt-get update

      - uses: fanatid/rust-github-ci-prepare@master
        with:
          cache-version: v0001-test

      - name: cargo deny check advisories
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check advisories

      - name: run clippy
        run: cargo clippy --all-targets -- -Dwarnings

      - name: run test
        run: cargo test --all-targets
